### ISSUE TITLE
The FLOPs of DecomposedConv2D

### ISSUE THREAD

**Issue by GoldenSpark** [timlee0212/PENNI#1]
The FLOPs of DecomposedConv2D is calculated according to function forward_test(), while the practical inference uses function forward(). Could you please explain it in details?

**Comment by GoldenSpark** [comment]
The function forward_test() can not work during the inference, due to  the wrong number of groups in F.conv2d()

**Comment by timlee0212** [comment]
Hi! Thank you for your attention and sorry for the late reply...

I have fixed the function and it should work now. 

We use the forward() instead of forward_test() since it's more efficient with the current implementation of the PyTorch. Although the forward_test() has fewer FLOPS, in theory, there's no CUDA kernel or MKL implementation that can efficiently implement this scheme. So we fallback to the forward() function during the training and testing.

We have ongoing works to explore the efficient hardware implementation of the proposed scheme.
