### ISSUE TITLE
'.h5' File Open Error in Pytorch

### ISSUE THREAD

**Issue by INCHEON-CHO** [timlee0212/PENNI#3]
I tried to load 'ResNet56s_9338.h5' file to checking number of weights. -> `torch.load('./ResNet56s_9338.h5')`

But error is occured like this. -> `ModuleNotFoundError: No module named 'models.resnet_s' `

How can I load checkpoint '.h5' file with pytorch?

And can you provide another types of checkpoint file such as '.pth'?

**Comment by timlee0212** [comment]
Hi! Thanks for your attention.
As I wrote in the notebook since the ResNet56 implementation I used was implemented with a lambda function, both pickle and Pytorch cannot serialize the model. You need to use **dill** to load the model. It has the same interface as pickle.

In addition, I think the error is because your current folder is not the project folder so that the deserialization process cannot locate the source code.

As for the pth code, because the decomposed model has some dynamic modifications on the original model structure, it might not work to just save the state_dict.

**Comment by INCHEON-CHO** [comment]
Thank you, I will try it!
